name: Reusable docker publish

on:
  pull_request:
    types: [ opened ]
    branches:
      - master
#  pull_request:
#    types: [ closed ]
#    branches:
#      - master
#  workflow_dispatch:

#      changeLookUpPath:
#        description: 'Which folder to look for changes and publish'
#        default: '**/'
#        required: false
#        type: string

jobs:
  run:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none
          tools: phpcs
      - name: Composer init
        uses: php-actions/composer@v6
        with:
          container_workdir: ${{ github.workspace }}
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          php_codesniffer: true
      - name: Run tests
        uses: php-actions/phpunit@v3
        with:
          version: 9.6
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
#      - name: Build and Push Docker images
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          REPOSITORY_OWNER: ${{ github.repository_owner }}
#        run: |
#          echo "ğŸ—ğŸ—ğŸ—ï¸  Building api-rails..."
#          if [ -f "Dockerfile" ]; then
#            echo "ğŸ”ğŸ”ğŸ”  Found Dockerfile for funpay"
#            image_name=ghcr.io/$REPOSITORY_OWNER/funpay:latest
#            docker build -f Dockerfile . -t $image_name --quiet
#            echo $GITHUB_TOKEN | docker login ghcr.io -u $REPOSITORY_OWNER --password-stdin
#            docker push $image_name --quiet
#            echo "âœ…âœ…âœ… Pushed successfully $image_name"
#          else
#            echo "âââ  No Dockerfile for $package found, skipping"
#          fi
